

name: GitHub Actions Maven Build Example

on:
  push:
    branches: [ "master" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
    - uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Have GitHub Actions Build Maven Project
      run: mvn -B package --file pom.xml
    - name: Step 4 - List the current directory
      run: ls -a
    - name: Step 5 - What is in the target folder?
      run: |
       cd  target
       ls -a
